server:
  # 端口
  port: 1234

spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  resources:
    # 静态资源访问路径
    static-locations: classpath:static/,classpath:resources/
  thymeleaf:
    # 页面热部署
    cache: true
  # 热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    # 服务地址
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（ms)
    timeout: 1000ms

#    # 高版本springboot中lettuce
#    jedis:
#      pool:
#      # 连接池最大连接数（负值表示无限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（负值无限制)
#      max-wait: 5000
#      # 最大空闲链接数
#      max-idle: 8
#      # 最小空闲链接数
#      min-idle: 0

# Mybatis配置
mybatis:
  mapper-locations: classpath:com/yy/domain/dao/food/*.xml
  type-aliases-package: classpath:com.yy.domain.model.entity
  # 驼峰命名规范
  configuration:
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置 日志级别 trace<debug<info<warn<error
logging:
  level.com.yy.domain.dao: debug
#  level.com.yy: warn
#  pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}: %msg%n"