server:
  # 端口
  port: 8081

spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

# Mybatis配置
mybatis:
  mapper-locations: classpath:com/yy/domain/dao/food/*.xml
  type-aliases-package: classpath:com.yy.domain.model.entity
  # 驼峰命名规范
  configuration:
    map-underscore-to-camel-case: true

# 日志配置 日志级别 trace<debug<info<warn<error
logging:
  level.root: warn
  llevel.com.yy: warn
#  pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}: %msg%n"